#!/bin/bash
# 🚀 Script pour publier BaseLearn sur GitHub

echo "📋 Instructions pour publier BaseLearn sur GitHub"
echo "=================================================="
echo ""
echo "1. Créez un nouveau repository sur GitHub.com :"
echo "   - Nom: BaseLearn"
echo "   - Description: Complete Base Learn curriculum - 135+ tests, 5 verified contracts"
echo "   - Public ✅"
echo "   - Ne PAS initialiser avec README ❌"
echo ""
echo "2. Copiez ces commandes (remplacez VOTRE-USERNAME) :"
echo ""
echo "# Connecter au repository GitHub"
echo "git remote add origin https://github.com/VOTRE-USERNAME/BaseLearn.git"
echo "git branch -M main"
echo ""
echo "# Remplacer README.md par la version GitHub"
echo "mv README.md README-ORIGINAL.md"
echo "mv README-GITHUB.md README.md"
echo "git add README.md"
echo "git commit -m '📚 Update README for GitHub'"
echo ""
echo "# Pousser vers GitHub"
echo "git push -u origin main"
echo ""
echo "🎉 Votre projet sera public sur :"
echo "https://github.com/VOTRE-USERNAME/BaseLearn"
echo ""
echo "🔒 SÉCURITÉ CONFIRMÉE :"
echo "✅ .env (avec vraies clés) est ignoré par .gitignore"
echo "✅ .env.public (sans clés) sera public - SÉCURISÉ"
echo "✅ Toutes les clés privées protégées"
echo ""
echo "📊 CONTENU PUBLIC :"
echo "✅ 5 contracts vérifiés avec liens Blockscout"
echo "✅ 135+ tests complets"
echo "✅ Documentation professionnelle"
echo "✅ Scripts de déploiement"
echo "✅ Structure de projet complète"